PROJECT_FOLDER_TREE = {
    "00. Proposal (Upto Quotation Stage)": {
        "01. Final Offer_Quote": {},
    },
    "01. Process": {
        "01. Basis of Design": {},
        "02. Process Description": {},
        "03. Heat and Mass Balance": {},
        "04. Equipment List": {},
        "05. Process Flow Diagram": {},
        "06. Utility Flow Diagram": {},
        "07. Piping & Instrumentation Diagram": {},
        "08. Utility Summary": {},
        "09. Line List": {},
        "10. Line Sizing": {},
        "11. Equipment Datasheet": {},
        "12. Calculations": {},
        "13. Simulation Files": {},
        "14. General Arrangement Drawings": {},
        "15. Control Philosophy": {},
        "16. Internal Checkprints": {},
        "17. HAZOP": {},
    },
    "02. Piping": {
        "01. Plant Layout": {},
        "02. Plant 3D": {},
        "03. Piping Isometric": {},
        "04. Bill of Materials": {},
        "05. Skid-Structure Details": {},
    },
    "03. Instrumentation": {
        "01. Instrument List": {},
        "02. Instrument Datasheets": {},
        "03. Functional Specification": {
            "01. HMI Screen List and Navigation Structure": {},
            "02. Alarm List": {},
            "03. PLC Programming Strategy": {},
        },
        "08. Software Backups": {
            "01. PLC": {},
            "02. HMI": {},
            "03. SCADA": {},
        },
    },
    "04. Electrical": {
        "01. System Description": {},
        "02. IO List": {},
        "03. IO Summary": {},
        "04. System Architecture": {},
        "05. Load List": {},
        "06. Electrical Drawing": {},
        "07. Panel GA": {},
        "08. Bill of Materials": {},
        "09. Cable Schedule": {},
        "10. Panel Inspection and Test Plan": {},
        "11. Heat Dissipation Calculation": {},
        "12. SCCR": {},
    },
    "05. Project": {
        "00. Client PO": {},
        "01. Project Schedule": {},
        "02. Project Philosophy": {},
        "03. Project Scope": {},
        "04. Documents Received from Clients": {},
        "05. Project Document Control Register (DCR)": {},
        "06. Kick Off Meeting": {},
        "07. MoM with Client": {},
        "08. Client Review - Comments": {},
        "09. Client Approvals": {},
        "10. Project Status": {},
        "11. Project Closure Documents": {},
        "12. Lessons Learnt": {},
        "13. Risk Register": {},
        "14. Change Requests": {},
    },
    "06. Procurement": {
        "01. Vendor Quotations": {},
        "02. Purchase Orders": {},
        "03. Vendor Evaluation": {},
        "04. Delivery Tracking": {},
    },
    "07. Quality": {
        "01. Vendor Documents": {
            "01. Manuals": {},
            "02. Calibration Certificates": {},
            "03. Communication Settings": {},
            "04. Test Reports": {},
        },
        "03. Project Operational Manual": {},
        "04. Photos": {},
        "05. Videos": {},
        "06. Voice Recordings": {},
        "07. Approved Drawing by Instron": {},
        "08. Approved Drawing by Client": {},
        "09. Inspection Reports": {},
        "10. Factory Acceptance Test": {},
        "11. Site Acceptance Test": {},
    },
    "08. Other Documentation": {
        "01. Dispatch Documents": {},
        "02. Export & Import Custom Clearance Documents": {},
    },
    "09. IT": {
        "01. Site Backups": {
            "01. Python Scripts": {},
            "02. Mail Utility": {},
            "03. Local Host": {},
            "04. DB Backup": {},
            "05. Backend Datalog Application": {},
        },
        "02. Solution Backups": {
            "01. Python Scripts": {},
            "02. Mail Utility": {},
            "03. Local Host": {},
            "04. DB Backup": {},
            "05. Backend Datalog Application": {},
        },
        "03. Documentation": {
            "01. Architecture Diagrams": {},
            "02. Deployment Instructions": {},
            "03. Change Logs": {},
            "04. License Keys": {},
        },
    },
}
